version: '3.8'
services:
  movies:
    image: dileep22/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  trains:
    image: dileep22/paydth:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: dileep22/paytrains:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: dileep22/payrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
